openapi: 3.0.0

info:
  title: "Strategic Organizational Restructuring API"
  description: "Analyzes legal staff data, calculates weighted merit scores, and generates restructuring reports."
  version: "1.0.0"

servers:
  - url: https://folly-uninfusing-zaire.ngrok-free.dev

paths:
  /generate-restructuring-report:
    post:
      summary: "Process staff data and generate strategic report"
      operationId: "generateReport"
      description: "Accepts raw employee JSON, runs weighted scoring algorithms, ranks staff for HQ vs Remote, and identifies financial risks."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - employees
              properties:
                employees:
                  type: array
                  items:
                    type: object
                    required:
                      - Name
                      - rating
                      - talent
                      - studii
                      - dupa salary
                      - jobul
                    properties:
                      Name:
                        type: string
                        example: "Alice Sterling"
                      rating:
                        type: number
                        format: float
                        description: "Performance rating (0.0 - 5.0)"
                        example: 4.8
                      talent:
                        type: string
                        description: "Talent assessment (High, Medium, Low)"
                        example: "High"
                      studii:
                        type: string
                        description: "Education level"
                        example: "PhD"
                      dupa salary:
                        type: integer
                        description: "Current annual salary"
                        example: 180000
                      jobul:
                        type: string
                        description: "Current Job Title"
                        example: "Senior Partner"
      responses:
        '200':
          description: "Report Generated Successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  structured_data:
                    type: object
                    description: "The raw JSON output from the Python ranking node"
                  strategic_report:
                    type: string
                    description: "The Markdown formatted text report generated by the LLM"